name: leo
description: A Flutter app for deepfake detection
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'  # Updated to support Dart 3.x

analyzer:
  enable-experiment:
    - super-parameters

dependencies:
  flutter:
    sdk: flutter
  intl: ^0.18.0
  firebase_core: ^2.14.0
  cloud_firestore: ^4.17.5
  firebase_storage: ^11.0.0
  image_picker: ^0.8.4+4
  tflite_flutter: ^0.11.0
  path_provider: ^2.0.11
  image: ^3.0.1


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.9.2  # Added flutter_launcher_icons for app icons

flutter:
  uses-material-design: true
  assets:
    - assets/models/MODEL.tflite
    - assets/labels.txt

# App icon configuration
flutter_icons:
  android: true
  ios: true
  image_path: "assets/image/logo.png"
